version: '3'
services:
  authelia-backend:
    image: authelia:dist
    labels:
      # Traefik 1.x
      - 'traefik.frontend.rule=Host:login.example.com;PathPrefix:/api'
      - 'traefik.protocol=https'
      # Traefik 2.x
      - 'traefik.http.routers.authelia_backend.rule=Host(`login.example.com`) && PathPrefix(`/api`) || Host(`login.example.com`) && PathPrefix(`${PathPrefix}/api`)'
      - 'traefik.http.routers.authelia_backend.entrypoints=https'
      - 'traefik.http.routers.authelia_backend.tls=true'
      - 'traefik.http.services.authelia_backend.loadbalancer.server.scheme=https'
    volumes:
      - '../..:/authelia'
    environment:
      - ENVIRONMENT=dev
    restart: always
    healthcheck:
      test: curl --insecure -f https://localhost:9091/${PathPrefix}/api/health || exit 1
    networks:
      authelianet:
        ipv4_address: 192.168.240.50
