---
services:
  redis-node-0:
    image: redis:7.2-alpine
    command: /entrypoint.sh master
    expose:
      - "6379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/users.acl:/data/users.acl
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-node-0.example.com
        ipv4_address: 192.168.240.110
  redis-node-1:
    image: redis:7.2-alpine
    command: /entrypoint.sh slave
    depends_on:
      - redis-node-0
    expose:
      - "6379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/users.acl:/data/users.acl
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-node-1.example.com
        ipv4_address: 192.168.240.111
  redis-node-2:
    image: redis:7.2-alpine
    command: /entrypoint.sh slave
    depends_on:
      - redis-node-0
    expose:
      - "6379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/users.acl:/data/users.acl
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-node-2.example.com
        ipv4_address: 192.168.240.112
  redis-sentinel-0:
    image: redis:7.2-alpine
    command: /entrypoint.sh sentinel
    depends_on:
      - redis-node-1
      - redis-node-2
    expose:
      - "26379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-sentinel-0.example.com
        ipv4_address: 192.168.240.120
  redis-sentinel-1:
    image: redis:7.2-alpine
    command: /entrypoint.sh sentinel
    depends_on:
      - redis-node-1
      - redis-node-2
    expose:
      - "26379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-sentinel-1.example.com
        ipv4_address: 192.168.240.121
  redis-sentinel-2:
    image: redis:7.2-alpine
    command: /entrypoint.sh sentinel
    depends_on:
      - redis-node-1
      - redis-node-2
    expose:
      - "26379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      authelianet:
        aliases:
          - redis-sentinel-2.example.com
        ipv4_address: 192.168.240.122
...
