---
# yaml-language-server: $schema=v
api:
  dashboard: true
  debug: false
  insecure: false

log:
  level: DEBUG

accessLog: {}

global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  https:
    address: ":8080/tcp"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /config/dynamic/
    watch: true
...
