language: node_js
node_js:
- '9'
services:
- docker
- ntp
addons:
  chrome: stable
  apt:
    sources:
    - google-chrome
    packages:
    - libgif-dev
    - google-chrome-stable
  hosts:
  - admin.example.com
  - login.example.com
  - single_factor.example.com
  - dev.example.com
  - home.example.com
  - mx1.mail.example.com
  - mx2.mail.example.com
  - public.example.com
  - authelia.example.com
  - admin.example.com

before_install:
- npm install -g npm@'>=2.13.5'
- pushd client && npm install && popd

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- "./scripts/authelia-scripts travis"
after_success:
- "./scripts/authelia-scripts publish-docker"

deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  skip_cleanup: true
  api_key:
    secure: GozHZ8/nk56lXzV9N+ywzgfUr89Qths9BDrD5vMR8FtvzH6KMLClgQHv9I/eLkmvCrhRkamyG9u7hgKaBrwQXewNAtJqrPKW/mmY+90NxFWRljsVqnvc0YWwA9FpgniPvbN/AY4qpiELp48lOLIB1X9WgTI4LUJ0j8QoadUUiK9mzZmVo6RXkY2OZfji8J4vxoOdyRmhN+sRcncYztR+H39xUatGLN50UOieXCmsN8fp/gQUVgF3HwebWEVocZ6tbjyVUkpInYEEAeA4DheUw11S0xt9nxNweM9XYG2LUqYSr8JIhbtEUmjyC8tQC+MqitHQBf91xctZnenmjCmpmrlAc6JLFkN5wYOCqpz4ZlxgDwKznqnldqgLfhCtFq8kp032KQr3XpH0nur8ccRqXNGKn32CmijprgCRYanXn7R84XOA/TleGUFWDqO+tPZjBQ1ob8y+SQpMhK+AbTnFWccXUb7PlCJ5UFAyejyrrmn2fDlp3ofqunk2siv5e3fn20uVLUk6assaybclFGlSy3xDTqOApTXvSAIaUfMtV2VnNH9FwhlhmPh4DgG2ph/nInW9pQh3ku5zaUcaPWaMYF5Pk3S3mwvCWr9eGAX+NDyJlLMIAq3nZr+v0450J3VEOs23GTdIAJnJrDy5L0TVdWEcP4cLAv32q1OkQJD947Y=
  on:
    tags: true
    repo: clems4ever/authelia
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
