[[main]]
  name = "Overview"
  identifier = "overview"
  url = "/overview/prologue/introduction/"
  weight = 10

[[main]]
  name = "Configuration"
  identifier = "configuration"
  url = "/configuration/prologue/introduction/"
  weight = 20

[[main]]
  name = "Integration"
  identifier = "integration"
  url = "/integration/prologue/introduction/"
  weight = 30

[[main]]
  name = "Contributing"
  identifier = "contributing"
  url = "/contributing/prologue/introduction"
  weight = 40

[[main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 50

[[main]]
  name = "Roadmap"
  identifier = "roadmap"
  url = "/roadmap/prologue/introduction/"
  weight = 80

[[main]]
  name = "Reference"
  identifier = "reference"
  url = "/reference/prologue/introduction/"
  weight = 90

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/authelia/authelia"
  post = "v0.1.0"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  url = "/policies/privacy"
  weight = 10

[[footer]]
  name = "Security Policy"
  url = "/policies/security"
  weight = 20

[[footer]]
  name = "Code of Conduct"
  url = "/code-of-conduct"
  weight = 30

[[footer]]
  name = "Contact"
  url = "/information/contact"
  weight = 40
