###############################################################
#                Authelia minimal configuration               #
###############################################################

port: 9091

logs_level: debug

jwt_secret: unsecure_secret

authentication_backend:
  file:
    path: /var/lib/authelia/users.yml

session:
  secret: unsecure_session_secret
  domain: example.com
  expiration: 3600000 # 1 hour
  inactivity: 300000 # 5 minutes

storage:
  local:
    path: /tmp/authelia/db.sqlite

# The Duo Push Notification API configuration
duo_api:
  hostname: duo.example.com
  integration_key: ABCDEFGHIJKL
  secret_key: abcdefghijklmnopqrstuvwxyz123456789

access_control:
  default_policy: bypass
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "secure.example.com"
      policy: two_factor

notifier:
  smtp:
    host: smtp
    port: 1025
    sender: admin@example.com
