---
services:
  authelia-backend:
    volumes:
      - './LDAP/configuration.yml:/config/configuration.yml'
      - './common/pki:/pki'
      - './common/pki/public.crt:/certs/public.crt'
      - '/tmp:/tmp'
...
