---
version: '3'
services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=authelia
    networks:
      - authelianet
...
