# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

---
version: '3'
services:
  oidc-client:
    image: ghcr.io/authelia/oidc-tester-app:master-aeac7f4
    command: /entrypoint.sh
    depends_on:
      - authelia-backend
    volumes:
      - ./example/compose/oidc-client/entrypoint.sh:/entrypoint.sh
    expose:
      - 8080
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.oidc.rule=Host(`oidc.example.com`)'
      - 'traefik.http.routers.oidc.priority=150'
      - 'traefik.http.routers.oidc.tls=true'
      - 'traefik.http.routers.oidc.middlewares=authelia@docker'
    networks:
      - authelianet
...
