# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

---
version: '3'
services:
  haproxy:
    image: authelia/integration-haproxy
    volumes:
      - ./example/compose/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./example/compose/haproxy/http.lua:/usr/local/etc/haproxy/haproxy-lua-http/http.lua
      - ./example/compose/haproxy/auth-request.lua:/usr/local/etc/haproxy/auth-request.lua
      - ./common/pki:/pki
    networks:
      authelianet:
        # Set the IP to be able to query on port 8080
        ipv4_address: 192.168.240.100
...
