---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: authelia-tls
    hosts:
    - login.example.com
  rules:
  rules:
  - host: login.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: authelia-service
          servicePort: 80
