---
services:
  k3d:
    image: ghcr.io/k3d-io/k3d:5.6.3-dind
    volumes:
      - './example/kube:/authelia'
      - './example/kube/authelia/configs/configuration.yml:/configmaps/authelia/configuration.yml'
      - './common/pki:/configmaps/authelia/ssl'
      - './example/compose/ldap/ldif:/configmaps/ldap'
      - './example/compose/nginx/backend:/configmaps/nginx-backend'
    privileged: true
    networks:
      authelianet:
        aliases:
          - public.example.com
          - secure.example.com
          - login.example.com
          - admin.example.com
          - dev.example.com
          - mail.example.com
          - kubernetes.example.com
          - traefik.example.com
        # Set the IP to be able to query on port 443
        ipv4_address: 192.168.240.100
...
