---
###############################################################
#                Authelia minimal configuration               #
###############################################################

theme: 'grey'

server:
  address: 'tcp://:9091'
  tls:
    certificate: '/pki/public.backend.crt'
    key: '/pki/private.backend.pem'

log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: 'a_very_important_secret'

authentication_backend:
  ldap:
    address: 'ldap://sambaldap'
    implementation: 'activedirectory'
    tls:
      skip_verify: true
    start_tls: true
    base_dn: 'DC=example,DC=com'
    additional_users_dn: 'OU=Users'
    additional_groups_dn: 'OU=Groups'
    user: 'CN=Administrator,CN=Users,DC=example,DC=com'
    password: 'password'

session:
  secret: 'unsecure_session_secret'
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  remember_me: 1y
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://login.example.com:8080'
      default_redirection_url: 'https://home.example.com:8080/'

storage:
  encryption_key: 'a_not_so_secure_encryption_key'
  local:
    path: '/config/db.sqlite3'

totp:
  issuer: 'example.com'
  disable_reuse_security_policy: true

access_control:
  default_policy: 'deny'
  rules:
    - domain: ["home.example.com", "public.example.com"]
      policy: 'bypass'
    - domain: "deny.example.com"
      policy: 'deny'
    - domain: "admin.example.com"
      policy: 'two_factor'
    - domain: "secure.example.com"
      policy: 'two_factor'
    - domain: "singlefactor.example.com"
      policy: 'one_factor'

regulation:
  max_retries: 3
  find_time: 300
  ban_time: 900

notifier:
  smtp:
    address: 'smtp://smtp:1025'
    sender: 'admin@example.com'
    disable_require_tls: true
...
