###############################################################
#                Authelia minimal configuration               #
###############################################################

logs_level: debug

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml

session:
  secret: unsecure_session_secret
  domain: example.com

# Configuration of the storage backend used to store data and secrets. i.e. totp data
storage:
  local:
    path: /etc/authelia/storage

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
totp:
  issuer: example.com

# Access Control
#
# Access control is a set of rules you can use to restrict user access to certain 
# resources.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  default_policy: deny

  rules:
    - domain: traefik.example.com
      policy: two_factor
    - domain: who.example.com
      policy: two_factor

# Configuration of the authentication regulation mechanism.
regulation: 
  # Set it to 0 to disable max_retries.
  max_retries: 3

  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window. 
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Default redirection URL
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
#default_redirection_url: https://authelia.example.domain

notifier:
  # For testing purpose, notifications can be sent in a file
  filesystem:
    filename: /tmp/authelia/notification.txt
