---
services:
  openldap:
    image: 'osixia/openldap:1.5.0'
    hostname: 'ldap.example.com'
    environment:
      LDAP_ORGANISATION: 'MyCompany'
      LDAP_DOMAIN: 'example.com'
      LDAP_ADMIN_PASSWORD: 'password'
      LDAP_CONFIG_PASSWORD: 'password'
      LDAP_ADDITIONAL_MODULES: 'memberof'
      LDAP_ADDITIONAL_SCHEMAS: 'openldap'
      LDAP_FORCE_RECONFIGURE: 'true'
      LDAP_TLS_VERIFY_CLIENT: 'try'
      LDAP_TLS_ENFORCE: 'true'
    volumes:
      - './example/compose/ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom'
      - './common/pki/private.ldap.pem:/container/service/slapd/assets/certs/ldap.key'
      - './common/pki/public.ldap.crt:/container/service/slapd/assets/certs/ldap.crt'
      - './common/pki/ca/public.crt:/container/service/slapd/assets/certs/ca.crt'
    command:
      - '--copy-service'
      - '--loglevel'
      - 'debug'
    networks:
      authelianet: {}
...
