title: Authelia
email: clement.michaud34@gmail.com
description: Authelia is an open source multi-factor single sign-on portal for web applications
url: "https://docs.authelia.com"
repository: https://github.com/authelia/authelia
logo: ./images/authelia-title.png
footer_content: "Copyright &copy; 2020 Authelia. Distributed by an <a href=\"https://github.com/authelia/authelia/blob/master/LICENSE\">Apache 2.0 license.</a>"
markdown: kramdown
theme: just-the-docs
keep_files:
  - .git
  - CNAME