title: Authelia
email: clement.michaud34@gmail.com
description: Authelia is an open source multi-factor single sign-on portal for web applications
# We need this base URL to serve the docs under https://www.authelia.com/docs/
baseurl: "/docs/"
# url: "https://www.authelia.com"
repository: https://github.com/authelia/authelia
logo: ./images/authelia-title.png
footer_content: "Copyright &copy; 2021 Authelia. Distributed by an <a href=\"https://github.com/authelia/authelia/blob/master/LICENSE\">Apache 2.0 license.</a>"
markdown: kramdown
theme: just-the-docs
keep_files:
  - .git
  - CNAME
ga_tracking: UA-124926127-1
