---
services:
  redis:
    image: 'redis:8.6-alpine'
    command: '/entrypoint.sh master'
    volumes:
      - './example/compose/redis/templates:/templates'
      - './example/compose/redis/users.acl:/data/users.acl'
      - './example/compose/redis/entrypoint.sh:/entrypoint.sh'
    networks:
      authelianet: {}
...
