---
services:
  redis:
    image: redis:7.2-alpine
    command: /entrypoint.sh master
    expose:
      - "6379"
    volumes:
      - ./example/compose/redis/templates:/templates
      - ./example/compose/redis/users.acl:/data/users.acl
      - ./example/compose/redis/entrypoint.sh:/entrypoint.sh
    networks:
      - authelianet
...
