# SPDX-FileCopyrightText: 2019 Authelia
#
# SPDX-License-Identifier: Apache-2.0

---
version: '3'
services:
  caddy:
    # build: ./example/compose/caddy/ # used for debugging
    image: caddy:2.6.4-alpine
    volumes:
      - ./example/compose/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      authelianet:
        ipv4_address: 192.168.240.100
...
