---
name: 'Scorecard'

on:
  branch_protection_rule: {}
  schedule:
    - cron: '39 23 * * 0'
  push:
    branches:
      - 'master'

permissions: 'read-all'

jobs:
  analysis:
    name: 'Analysis'
    runs-on: 'ubuntu-latest'
    if: github.event.repository.default_branch == github.ref_name
    permissions:
      security-events: 'write'
      id-token: 'write'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a  # v2.13.1
        with:
          egress-policy: audit
      - name: 'Checkout'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
      - name: 'Analyze'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a  # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "write" PAT token. Uncomment the `repo_token` line below if:
          # - you want to enable the Branch-Protection check on a *public* repository, or
          # - you are installing Scorecard on a *private* repository
          # To create the PAT, follow the steps:
          #   https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

          publish_results: true

          # (Optional) Uncomment file_mode if you have a .gitattributes with files marked export-ignore
          # file_mode: git
      - name: 'Upload Results to Job'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  # v5.0.0
        with:
          name: 'SARIF file'
          path: 'results.sarif'
          retention-days: 5
      - name: 'Upload Results to Dashboard'
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047  # v4.30.9
        with:
          sarif_file: 'results.sarif'
...
