---
name: 'Scorecard'

# yamllint disable-line rule:truthy
on:
  branch_protection_rule: {}
  schedule:
    - cron: '39 23 * * 0'
  push:
    branches:
      - 'master'

permissions: 'read-all'

jobs:
  analysis:
    name: 'Analysis'
    runs-on: 'ubuntu-latest'
    if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
    permissions:
      security-events: 'write'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: 'Analyze'
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "write" PAT token. Uncomment the `repo_token` line below if:
          # - you want to enable the Branch-Protection check on a *public* repository, or
          # - you are installing Scorecard on a *private* repository
          # To create the PAT, follow the steps:
          #   https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

          publish_results: true

          # (Optional) Uncomment file_mode if you have a .gitattributes with files marked export-ignore
          # file_mode: git
      - name: 'Upload Results to Job'
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
        with:
          name: 'SARIF file'
          path: 'results.sarif'
          retention-days: 5
      - name: 'Upload Results to Dashboard'
        uses: github/codeql-action/upload-sarif@303c0aef88fc2fe5ff6d63d3b1596bfd83dfa1f9 # v3.30.4
        with:
          sarif_file: 'results.sarif'
...
