---
name: 'Scorecard'

on:
  branch_protection_rule: {}
  schedule:
    - cron: '39 23 * * 0'
  push:
    branches:
      - 'master'

permissions: 'read-all'

jobs:
  analysis:
    name: 'Analysis'
    runs-on: 'ubuntu-latest'
    if: github.event.repository.default_branch == github.ref_name
    permissions:
      security-events: 'write'
      id-token: 'write'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76  # v2.14.0
        with:
          egress-policy: audit
      - name: 'Checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - name: 'Analyze'
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a  # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "write" PAT token. Uncomment the `repo_token` line below if:
          # - you want to enable the Branch-Protection check on a *public* repository, or
          # - you are installing Scorecard on a *private* repository
          # To create the PAT, follow the steps:
          #   https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

          publish_results: true

          # (Optional) Uncomment file_mode if you have a .gitattributes with files marked export-ignore
          # file_mode: git
      - name: 'Upload Results to Job'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: 'SARIF file'
          path: 'results.sarif'
          retention-days: 5
      - name: 'Upload Results to Dashboard'
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89  # v4.31.10
        with:
          sarif_file: 'results.sarif'
...
